### ISSUE TITLE
Have website documentation be markdown based

### ISSUE THREAD

**Issue by pascalwhoop** [open-covid19/website#3]
Can we have the website pull in data from markdown files and render them as html? This would avoid us writing things first in markdown and then having to copy to the website code. We can then have a `docs` folder where we place a list of pages and these get rendered as pretty html for the readers. 

https://www.mkdocs.org/ Can do that and 
An example is 
https://github.com/python-poetry/poetry/tree/master/docs

Which results in 

https://python-poetry.org/docs/

**Comment by remondevries** [comment]
I be able to take a look at this and see if I be able to build this in, currently also working on updating the website for mobile etc.
