### ISSUE TITLE
Bring some graphs onto website

### ISSUE THREAD

**Issue by pascalwhoop** [open-covid19/website#4]
@melaniam can you bring some of your graphs together with this website? Feel free to change anything you want! 
One I find most interesting is to plot the increase rate over time. Ideally, we'd have the "top 10 countries excluding china" (because they made it already, they seem to have solved it for themselves) plotted together. That way we can see if italy and korea have solved it after their lockdowns and how other countries are doing (like half of Europe which seems to be doing rather badly at the moment)

**Comment by melaniam** [comment]
Yes, I'll use the weekend time to do that. There is one issue though, I used React to create my page - that's easy to change. But I also used **'recharts'** (a React based library for charts) and that might be a bit more complex to update.

Is there anyone else with React knowledge on the front-end side of the team? Could we start with a React project, or should I follow a more "vanilla JS" approach?

**Comment by pascalwhoop** [comment]
Hi @melaniam 
what's your skill level? Not asking to judge, just to know how much I need to help or I can let you do on your own.
I'd add react to the project, or actually turn the whole page into a react app and then move the current landing page code in there.
Alternatively, I like gatsbyjs.org/ (which I use for my personal website) [here](github.com/pascalwhoop/pascalbrokmeier.de). It's a react based website framework and it would allow us to
- write in markdown
- develop with react
- have both static and dynamic content in pages

I can take care of CICD and hosting for this. Just let me know how much you feel comfortable doing and where you need help.

**Comment by melaniam** [comment]
No worries, I totally understand your question. I have 10 years of experience as a software engineer (.NET dev for a few years, and Front-End dev afterwards), and spent the last 2.5 years working with React. 
I know about Gatsby, but never worked with it until now. I should be able to catch up quickly with Gatsby, so using either a generic React app or a Gatsby one is very good for me.

**Comment by melaniam** [comment]
@pascalwhoop I'm working to set up a new Gatsby project. I'd rather create a new repo for that, if you don't mind, and use the Gatsby CLI.

**Comment by remondevries** [comment]
@melaniam great to see more help on the website!

Do you have any ideas about how want to go about this? I was planning this today to go over some adjustments on the current page. Should we replace the current page with your application or should we split this up by using a landing page and graphs on a different part of the site?

**Comment by melaniam** [comment]
Hi @remondevries ! It depends on what you're familiar with, and what you prefer working with. If you're also fine with Gatsby.js, then we can go ahead and use that.

I'm working now to move my existing charts page into a new Gatsby project, but need to stop for a few hours, and will get back to it afterwards. I can create a new repo for the new app. There, we could have one page with the charts and any other pages that you were thinking about adding.

**Comment by remondevries** [comment]
@melaniam @pascalwhoop I think it might be a good idea to split this up. Have one page that contains info on how to use the API and have another to bring this data into Gatsby, I have not used Gatsby yet but that does not mean I might be able to figure this out. I be able to start adjusting things on the current code and make sure that there is room for your charts.

**Comment by melaniam** [comment]
@remondevries I will create a new repo and push the code that I have until now there. It still needs cleaning up, but it's something that can be used for now. I will add the link to it here in a few minutes.

I'm not sure how well the two types of apps work together, because from the looks of it, both are created using a CLI, and we would need to manually merge package.json and two styles of working (jquery/foundation/gulp vs gatsby/react). I'm perfectly fine with trying, though.

**Comment by melaniam** [comment]
@remondevries @pascalwhoop https://github.com/open-covid19/website-gatsby/tree/master/src

**Comment by pascalwhoop** [comment]
I will take care of merging. What I think is best is that I have the gatsby page as a separate page and the one created before as a simple static landing page. I also suspect that gatsby will subsume the first one in the medium term.
I should have a link to the new page done by the end of the day.

**Comment by melaniam** [comment]
@pascalwhoop the Gatsby page is now set up and working. 

I still kept the first 60 (~half of the total number of) countries in the descending order of the confirmed cases, because there might be some people interested in how their country is doing, even if it's not in the first 10. 

I'm thinking about adding a new stat on each chart: existing cases, and that way we could see better what's the actual status. 

What do you think about this?
